"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$cmd_duration$package$nodejs$rust$golang $time\
$line_break\
$character"""

add_newline = true

palette = "catppuccin_mocha"

[git_branch]
symbol = ""
format = "[$symbol $branch(:$remote_branch)]($style)"

[cmd_duration]
format = "took [$duration]($style) "

[nodejs]
symbol = ""
format = '[$symbol ($version)](text)'

[rust]
symbol = ""
format = '[$symbol ($version)](text)'

[golang]
symbol = ""
format = '[$symbol ($version)](text)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[  $time](subtext2)'

[character]
success_symbol = "[❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
truncation_length = 4
style = "bold lavender"

[package]
symbol = ""
format = "[$symbol $version](lavender) "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
crust = "#11111b"
mantle = "#181825"
